#!/usr/bin/env bash
# Golden-master harness: render every layout with the TS implementation and
# byte-compare against tests/golden/ (generated by the Python prototype at
# commit 2f46dd2 before its removal).
set -euo pipefail
cd "$(dirname "$0")/.."
rm -rf tests/out && mkdir -p tests/out
for f in layouts/*.ts; do ISOKIT_OUT="$PWD/tests/out" node "$f"; done
node src/cli.ts render examples/minimal.yaml -o tests/out/Minimal.svg
node src/cli.ts render examples/hybrid.yaml -o "tests/out/Hybrid Semantic.svg"
fail=0
for g in tests/golden/*.svg; do
  b="$(basename "$g")"
  if cmp -s "$g" "tests/out/$b"; then echo "IDENTICAL $b"
  else echo "DIFFERS   $b"; fail=1; fi
done
exit $fail
