// pyf() must reproduce Python f"{x:.{nd}f}" exactly. Every `want` below was
// generated by CPython, not by hand — regenerate with:
//   python3 -c 'print(f"{88.25:.1f}")' etc.
import { pyf } from "../src/isokit.ts";

const cases: [number, number, string][] = [
  [88.25, 1, "88.2"],
  [88.75, 1, "88.8"],
  [0.05, 1, "0.1"],
  [288.5, 0, "288"],
  [289.5, 0, "290"],
  [-0.04, 1, "-0.0"],
  [-0.0, 1, "-0.0"],
  [-0.0, 3, "-0.000"],
  [1.25, 1, "1.2"],
  [1.35, 1, "1.4"],
  [39.836, 1, "39.8"],
  [463.0, 1, "463.0"],
  [2.675, 2, "2.67"],
  [0.125, 2, "0.12"],
  [-88.25, 1, "-88.2"],
  [28.52, 0, "29"],
  [8.68, 0, "9"],
  [0.0, 1, "0.0"],
  [1e-12, 1, "0.0"],
  [123.456789, 3, "123.457"],
  [-1.5, 0, "-2"],
  [-2.5, 0, "-2"],
  [0.5, 0, "0"],
  [1.5, 0, "2"],
];

let fail = 0;
for (const [x, nd, want] of cases) {
  const got = pyf(x, nd);
  if (got !== want) {
    console.error(`pyf(${x}, ${nd}) = ${JSON.stringify(got)}, want ${JSON.stringify(want)}`);
    fail++;
  }
}
if (fail) process.exit(1);
console.log(`pyfmt: ${cases.length} cases ok`);
