// scripts/gen-fonts.ts — regenerate src/fonts.ts from the JetBrains Mono
// woff2 files (fontsource v5, latin subset). Run: node scripts/gen-fonts.ts
import * as fs from "node:fs";
import { execFileSync } from "node:child_process";

const URL = "https://cdn.jsdelivr.net/npm/@fontsource/jetbrains-mono@5/files/jetbrains-mono-latin-{w}-normal.woff2";

function b64(w: number): string {
  const p = `/tmp/jbm${w}.woff2`;
  if (!fs.existsSync(p)) execFileSync("curl", ["-sL", "-o", p, URL.replace("{w}", String(w))]);
  return fs.readFileSync(p).toString("base64");
}

fs.writeFileSync("src/fonts.ts",
  "// GENERATED by scripts/gen-fonts.ts — do not edit by hand.\n"
  + "// JetBrains Mono latin woff2 (fontsource v5), base64. Keeping these as\n"
  + "// constants is what lets svgOpen() run without filesystem access.\n"
  + `export const JBM400 = "${b64(400)}";\n`
  + `export const JBM700 = "${b64(700)}";\n`);
console.log("wrote src/fonts.ts", fs.statSync("src/fonts.ts").size, "bytes");
